name: Deploy Test Deployment

on: 
  push:
    branches: 
      - master
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    # env:
    #   SERVER: waws-prod-ln1-025.ftp.azurewebsites.windows.net

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
      
    - name: Install NPM Modules
      run: yarn install 
      

      

    - name: Build Project
      run: yarn run build:ssr
    
    - name: Sync Files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4

      with:
        username: smart-118
        server: 104.41.201.128
        local_path: './dist'
        remote_path: './sites/testDeployment2/'
        sftp_only: true
        password: f5T6uFbjPD$5kD9




    
        